pipeline {
    agent any

    stages {
        stage('Lint') {
            steps {
                dir('%WORKSPACE%\\text_analyzer') {
                    bat 'echo %WORKSPACE%'
                    bat 'task lint'
                }
            }
        }

        stage('Build Package') {
            steps {
                dir('..') {
                    bat 'task build ver=1.2.3'
                }
            }
        }


        stage('Test') {
            steps {
                dir('..') {
                    bat 'task test'
                }
            }
        }
    }
}
