pipeline {
    agent any

    stages {

        stage('Lint') {
            when{
                expression{isTagBuild()}
            }
            steps {
                dir('.\\text_analyzer') {
                    bat 'task lint'
                }
            }
        }

        stage('Build Package') {
            when{
                expression{isTagBuild()}
            }
            steps {
                dir('.\\text_analyzer') {
                    bat 'task clean'
                    bat 'task build ver=1.2.3'
                }
            }
        }


        stage('Test') {
            when{
                expression{isTagBuild()}
            }
            steps {
                dir('.\\text_analyzer') {
                    bat 'task test'
                }
            }
        }
    }
}


def isTagBuild() {
    def tagPattern = java.util.regex.Pattern.compile('^v\\d+\\.\\d+\\.\\d+$')

    echo "GIT_TAG env: ${env.GIT_TAG}"

    def tagOutput = '' // declare outside try so it's accessible after
    try {
        tagOutput = bat(
            script: 'git describe --tags --exact-match || echo ""',
            returnStdout: true
        ).trim()
    } catch (err) {
        echo "No tag detected, skipping stages."
        return false
    }

    def tag = tagOutput.readLines().last().trim()
    echo "Detected tag: ${tag}"

    return tag ==~ tagPattern
}
