def isTagBuild(){
    if (env.GIT_TAG && env.GIT_TAG != "") {
        return true
    }
    def tag = bat(script: 'git describe --exact-match --tags || exit 0', returnStdout: true).trim()
    return tag != "" && !tag.startsWith("fatal:")
}


pipeline {
    agent any

    stages {
        stage('Lint') {
            when{
                expression{isTagBuild()}
            }
            steps {
                dir('.\\text_analyzer') {
                    bat 'task lint'
                }
            }
        }

        stage('Build Package') {
            when{
                expression{isTagBuild()}
            }
            steps {
                dir('.\\text_analyzer') {
                    bat 'task build ver=1.2.3'
                }
            }
        }


        stage('Test') {
            when{
                expression{isTagBuild()}
            }
            steps {
                dir('.\\text_analyzer') {
                    bat 'task test'
                }
            }
        }
    }
}
